global using MayTheFourth.Application.Movies.Interfaces.Services;
global using MayTheFourth.Application.Movies.Services;
global using MayTheFourth.Application.Movies.Interfaces.State;
global using MayTheFourth.State.Movies;
global using MayTheFourth.Application.Peoples.Interfaces.Services;
global using MayTheFourth.Application.Peoples.Services;
global using MayTheFourth.Application.Peoples.Interfaces.State;
global using MayTheFourth.State.Peoples;
global using MayTheFourth.Web.Endpoints;